version: '3.8'

services:
  layout-pipeline:
    container_name: layout-pipeline
    build:
      context: .
      dockerfile: Dockerfile
    image: layout-pipeline:latest
    volumes:
      - ./data:/app/target/data