version: '3.8'

volumes:
  demaf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./volume
  winery:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./winery

services:

  # Message Broker
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: demaf-rabbitmq
    container_name: demaf-rabbitmq
    volumes:
      #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/logs:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  # Databases
  modelsdatabase:
    image: mongo:5.0.6
    hostname: modelsdatabase
    container_name: modelsdatabase
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tad
      MONGO_INITDB_ROOT_PASSWORD: tad
    ports:
      - 27017:27017

  configurationsdatabase:
    image: postgres:14.2
    hostname: configurationsdatabase
    container_name: configurationsdatabase
    restart: always
    environment:
      POSTGRES_USER: tad
      POSTGRES_PASSWORD: tad
      POSTGRES_DB: configurations
    ports:
      - 5432:5432

  tasksdatabase:
    image: postgres:14.2
    hostname: tasksdatabase
    container_name: tasksdatabase
    restart: always
    environment:
      POSTGRES_USER: tad
      POSTGRES_PASSWORD: tad
      POSTGRES_DB: tasks
    ports:
      - 5433:5432

  # Core Services
  analysismanager:
    image: well5a/analysis-manager:testing
    hostname: analysismanager
    container_name: analysismanager
    depends_on:
      - rabbitmq
      - configurationsdatabase
      - tasksdatabase
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.configurations-datasource.jdbcUrl": "jdbc:postgresql://configurationsdatabase:5432/configurations",
        "spring.configurations-datasource.username": "tad",
        "spring.configurations-datasource.password": "tad",
        "spring.tasks-datasource.jdbcUrl": "jdbc:postgresql://tasksdatabase:5432/tasks",
        "spring.tasks-datasource.username": "tad",
        "spring.tasks-datasource.password": "tad",
        "models-service.url": "http://modelsservice:8081",
        "spring.rabbitmq.host": "rabbitmq"
        }'
    ports:
      - 8080:8080

  modelsservice:
    image: well5a/models-service:latest
    hostname: modelsservice
    container_name: modelsservice
    depends_on:
      - modelsdatabase
    restart: always
    environment:
      SPRING_DATA_MONGODB_USERNAME: tad
      SPRING_DATA_MONGODB_PASSWORD: tad
      SPRING_DATA_MONGODB_DATABASE: modelsdatabase
      SPRING_DATA_MONGODB_HOST: modelsdatabase
      SPRING_DATA_MONGODB_PORT: 27017
      TADM_OUTPUT_DIRECTORY: /usr/share/tadms
    volumes:
      - demaf:/usr/share
    ports:
      - 8081:8081

  # Eclipse Winery
  winery:
    container_name: winery
    image: opentosca/radon-gmt:latest
    environment:
      PUBLIC_HOSTNAME: "localhost"
      WINERY_FEATURE_RADON: "true"
      WINERY_REPOSITORY_PROVIDER: "yaml"
    volumes:
      - winery:/var/repository
    ports:
      - 80:8080

  # Plugins
  layout-pipeline:
    container_name: layout-pipeline
    build:
      context: .
      dockerfile: Dockerfile
    image: layout-pipeline:latest
    depends_on:
      - analysismanager
    environment:
      ANALYSIS_MANAGER_PLUGIN_REGISTRATION_URL: http://analysismanager:8080/plugin-registration
      MODELS_SERVICE_URL: http://modelsservice:8081
      SPRING_RABBITMQ_HOST: rabbitmq
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - demaf:/usr/share
      - winery:/var/repository
    ports:
      - 8082:8082
      - 5005:5005